# Generated by Django 2.1.4 on 2018-12-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20181224_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='olsanka_id',
            field=models.IntegerField(default=1, verbose_name='ID in Olšanka hotel reservation system'),
            preserve_default=False,
        ),
    ]
