# Generated by Django 2.1.4 on 2019-01-06 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_sport_olsanka_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olsanka_id', models.IntegerField(verbose_name='Court ID in Olšanka reservation system')),
                ('name', models.CharField(max_length=60, verbose_name='Court name')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Sport')),
            ],
        ),
    ]
